---
title: "Spaghetti Code"
author: "Joshua Ferrer-Lozano"
date: "2025-08-26"
output: html_document
---
```{r}

library(janitor)
library(tidyr)
library(tidyverse)
library(paletteer)
library(dplyr)
library(here)
library(zoo)
```

```{r}
# import data sets 

data_1 <- read.csv(here('data','QuebradaCuenca1-Bisley.csv')) |> janitor::clean_names()
data_2 <- read.csv(here('data','QuebradaCuenca2-Bisley.csv')) |> janitor::clean_names()
data_3 <-read.csv(here('data','QuebradaCuenca3-Bisley.csv')) |> janitor::clean_names()

bisley_all <- bind_rows(data_1,data_2,data_3)

```

```{r}
bisley_all <- bisley_all %>% mutate(sample_date = as.Date(sample_date)) %>% arrange(sample_id, sample_date)
```

```{r}
bisley_all
```

```{r}
#originally was going to use rollmean function

#bisley_all$K_rm <- rollmean(bisley_all$K,9,fill=NA,align="center")
#bisley_all$NO3_rm <- rollmean(bisley_all$NO3.N,9,fill=NA,align="center")
#bisley_all$Mg_rm <- rollmean(bisley_all$Mg,9,fill=NA,align="center")
#bisley_all$Ca_rm <- rollmean(bisley_all$Ca,9,fill=NA,align="center")
#bisley_all$NH4_rm <- rollmean(bisley_all$NH4.N,9,fill=NA,align="center")
```

```{r}
bisley_long <- pivot_longer(bisley_all, cols = ends_with("_rm"),
          names_to = "nutrient", values_to = "value") %>%
  filter(!is.na(value))
```


```{r}
# 9 Month Moving Average
moving_average <- function(focal_date, Sample_Date, conc, wind_size_weeks) {
  #Which dates are in the window
  is_in_window <- (dates > focal_date - (wind_size_weeks / 2) * 7) &
    (dates < focal_date + (wind_size_weeks / 2) * 7)
  #find the associated concentrations
  window_conc <- conc[is_in_window]
  #calculate the mean
  result <- mean(window_conc)
  
  return(result)
}

```

```{r}

#Data is now clean, we need to now create a groupby only of our cleaned nutrients that were interested in
#nutrients <- bisley_all %>% 
#  group_by(sample_id) %>%
#  mutate(across(
#    c(k, no3_n, mg, ca, nh4_n)))
    #,
    #introducing the rollmean function that will section our years into 9 sections for the means
    
#Creating the rolling Mean
    
#    ~ rollmean(., k = 9, fill = NA, align = "right"),
#    .names = "{.col}_rollmean9"
#  )) %>%
#  ungroup()
```

```{r}
#bisley_all %>% 
  #wanted to verify that there were sums in our nutrient columns
#  summarise(across(c(k, no3_n, mg, ca, nh4_n),
#                   ~ sum(!is.na(.)), .names = "n_nonNA_{.col}"))
```

```{r}
#Finding rolling average for ca
nutrients$sample_date <- as.Date(nutrients$sample_date)

ca_ma_once <- moving_average(focal_date = as.Date("1986-05-20"),
                             Sample_Date = nutrients$sample_date,
                             conc = nutrients$ca,
                             wind_size_weeks = 9)
```


